services:
  - type: web_service
    name: etpms-ai-service
    env: docker
    branch: master
    dockerfilePath: ai-service/Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: "8000"

  - type: web_service
    name: etpms-backend
    env: docker
    branch: master
    dockerfilePath: BACKEND/ETPMS/Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: "8080"
      - key: AI_SERVICE_URL
        value: "https://etpms-ai-service.onrender.com"
      - key: CORS_ALLOWED_ORIGIN
        value: "https://etpms-frontend.onrender.com"
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://dpg-d75k57gule4c73csfjq0-a:5432/etpms_db"
      - key: SPRING_DATASOURCE_USERNAME
        value: "etpms_db_user"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "qnSE5zWqOWh2AUi0oD8YC7jNGWyEikjy"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "update"

  - type: static_site
    name: etpms-frontend
    env: node
    branch: master
    root: FRONTEND/eptms
    plan: starter
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://etpms-backend.onrender.com/api"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
